### ISSUE TITLE
@Chapter Node Handling?

### ISSUE THREAD

**Issue by tbpassin** [boltex/leojs#105]
I thought that there is chapter handling, but I don't see a way to select chapters.  Also, when I tried to hoist an `@chapter` node, I got this message:

`can not hoist an @chapter node`

Since the main point of having chapters is to be able list them and hoist them, This is disappointing.

**Comment by boltex** [comment]
@tbpassin Thanks for your interest in accessibility of the 'chapter' related commands! 😄 yes, there is chapter handling in LeoJS.

Every commands were transliterated directly from Leo's original python code.

All command icons will soon have their visibility and placement 100% customizable instead of being forced above the outline and body pane following completion of https://github.com/boltex/leojs/issues/72. 

In the meantime, they are easily accessible when starting to type the word 'chapter' in either the minibuffer **Alt+X** or VSCode's command palette **CTRL+SHIFT+P** _(command palette has **most** commands, while the minibuffer has **all** commands)_
![image](https://github.com/boltex/leojs/assets/847716/f8d96f13-4bc2-45eb-bac5-9cd620f75947)

You can also access them with the 'chapter-select' icon button, located above the body pane:
![image](https://github.com/boltex/leojs/assets/847716/2ed11633-421e-4d89-8a95-d970226f8308)

and all chapter related commands are also above the 'find panel' and the 'goto panel':
![image](https://github.com/boltex/leojs/assets/847716/f6c2589a-15ac-4d85-88fb-ac1a4bae7035)

Lastly, The `can not hoist an @chapter node` message when trying to hoist an @chapter node is consistent with Leo:
![image](https://github.com/boltex/leojs/assets/847716/010518d8-16a1-4026-b1e7-165183f3cc6a)

So all in all, the only place the chapter command icon is _not_ is above the outline pane... (there is a maximum number of icons allowed in vscode above each panels) Hope this helps ! 😄

**Comment by boltex** [comment]
Closed in favor of #72 which will allow personal preferences for specific command-icons over any panel.
