### ISSUE TITLE
Improve documentation about the default command keybindings

### ISSUE THREAD

**Issue by edreamleo** [boltex/leojs#128]
If focus is in the tree, `Tab` first selects the "Edit Headline" icon. Only afterwards does `Tab` select the body.

If focus is in the body, neither `Tab` nor `Enter` change focus. Insert they insert a character.

**Comment by boltex** [comment]
@edreamleo 

>If focus is in the tree, Tab first selects the "Edit Headline" icon. Only afterwards does Tab select the body.

I can't change this behavior, but I could perhaps make the 'edit' icon command on the nodes to be absent by default... Not sure yet what to think about this... I'll think about it. :)

>If focus is in the body, neither Tab nor Enter change focus. Insert they insert a character.

As it should, hehe, :) this is for the command to 'Focus on body', not to be executed when focus is on the body (Otherwise how would someone type an enter or a tab in the editor?) 

Please provide a screenshot (Shift+Windows Key+S) to drag and click. and the paste directly in here to illustrate which source you are reading those keybindings from so that I can understand exactly where those come from. 

(You referred in another issue about a 'keybinding list', a 'readme' and lastly a 'webpage'. All three for which I'm unsure if it's from the leojs repo, or Leo's repo, or some other webpage)

**Comment by edreamleo** [comment]
@boltex I think we agree about what is happening. This issue is only concerned with the *description* of the <tab> and <enter> keys.

In vs-code, in the description of LeoJS, in the "Keybindings" section, the entry for "Focus on Binding" is misleading.

![image](https://github.com/boltex/leojs/assets/592928/0f0820e1-6496-4b4a-842f-a89beb271ebb)

As you say, the `<tab>` and `<enter>` binding has effect *only if the focus is in the outline*. But the entry implies that these two bindings apply everywhere.

This is a minor point, but it actually confused me the first time!

I suggest splitting the "Focus on Body" line into two lines:

- Focus on Body (in any pane):  Alt-D or Ctrl-G
- Focus on Body (only in Outline Pane): Tab or Enter

Clear?

**Comment by edreamleo** [comment]
@boltex

> You referred in another issue about a 'keybinding list', a 'readme' and lastly a 'webpage'. All three for which I'm unsure if it's from the leojs repo, or Leo's repo, or some other webpage.

Imo, this question is moot. I have already closed #127 because the desired web page already exists, namely:
https://github.com/boltex/leojs

More specifically, this section: https://github.com/boltex/leojs?tab=readme-ov-file#keybindings

**Comment by edreamleo** [comment]
@boltex Note that the links to the readme above are in the master branch.  I think that's good enough.

**Comment by boltex** [comment]
@edreamleo The PR is now merged in the dev branch.

**Comment by edreamleo** [comment]
@boltex Thanks :-)
