### ISSUE TITLE
Add settings to customize visible command-icons over panels

### ISSUE THREAD

**Issue by edreamleo** [boltex/leojs#72]
I'm not a big fan of icons in general. Here are two (somewhat conflicting!) suggestions:

- Add an option to suppress the icons in the 'Outline' pane.
  These icons obscure the path, which imo is much more important.
  True, these icons disappear when focus is outside the 'Outline' are, but an option to dispense with them would be welcome.

- Add an icon/menu item to go to the `LeoJS: Welcome` pane.
  This would complement the standard "gear" icon.
  This suggestion is less important imo.

**Comment by boltex** [comment]
@edreamleo Thanks for those suggestion! 

I'll add option settings, _like I did for hover icons on the outline, shown below_, to have the user select which ones he wants to have above the outline pane, if any, and I'll also add this concept for the icons above the body pane editor.  😄 

![image](https://github.com/boltex/leojs/assets/847716/6f7a5c7c-3344-4b72-8583-7f5da094509e)

**Comment by edreamleo** [comment]
@boltex You're welcome :-)

**Comment by boltex** [comment]
Outline-pane icons are now customizable in devel branch. It the leojs-settings webview offers most outline structure-editing related command icons.

Since the body pane is _very limited in icon real-estate space_, I'll leave the 'prev/next', 'extract, extract names' and other body pane icons as they are, since they are related to the body pane textual content.
